In [20]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
from dnafiber.ui.utils import get_image_cacheless, get_model_cacheless, MODELS_ZOO
from dnafiber.ui.inference import inference_cacheless
from dnafiber.data.intergrader.analysis import (
    extract_properties_from_datadict,
    skeletonize_data_dict,
)
import numpy as np
from tqdm.auto import tqdm
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
modelname = list(MODELS_ZOO.keys())[1]
modelid = MODELS_ZOO[modelname]
device = "cuda"
model = get_model_cacheless(device, modelid)

list_files = list(Path("C:/Users/cleme/OneDrive/PostDoc/data/DNAFiber/Validation/").rglob("*.czi"))


In [22]:
output = dict()
output[modelname] = dict()
for i, file in enumerate(tqdm(list_files)):
    img = get_image_cacheless(file)
    results = inference_cacheless(model, img, device).astype(np.uint8)
    name = file.stem.split('-')[0]
    if name not in output[modelname]:
        output[modelname][name] = []
    output[modelname][name].append(results)
    torch.cuda.empty_cache()    

  0%|          | 0/43 [00:00<?, ?it/s]

2025-04-25 15:14:04.094 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
100%|██████████| 296/296 [00:30<00:00,  9.63it/s]
2025-04-25 15:14:54.514 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
100%|██████████| 370/370 [00:47<00:00,  7.72it/s]
2025-04-25 15:16:10.401 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
100%|██████████| 495/495 [00:50<00:00,  9.81it/s]
2025-04-25 15:17:23.172 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
100%|██████████| 208/208 [00:08<00:00, 23.32it/s]
2025-04-25 15:17:39.271 WARNING stre

In [23]:
skeletons = skeletonize_data_dict(output)
properties = extract_properties_from_datadict(skeletons, with_common_analysis=False)

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

In [25]:
import pandas as pd

df = pd.DataFrame.from_dict(properties)
df.to_pickle(f"{modelname}_properties.pkl")

In [ ]:
df = pd.read_pickle(f"{modelname}_properties.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'SegFormer MiT-B4_properties.csv'

In [ ]:
skeletons = skeletonize_data_dict(output)


  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

In [ ]:
output

{'segformer MiT-B2': {'siBRCA2': [array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
   array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
   array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
   array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
   array(